import React from 'react'
import Head from 'next/head'

const proyectos = () => {
    return (
        <>
            <Head>
                <title>Mis Proyectos</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>proyectos</div>
        </>
    )
}

export default proyectos