import React, { Fragment } from 'react'
import Head from 'next/head'



const sobremi = () => {
  return (
    <Fragment>
      <Head>
        <title>Sobre mi</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>sobremi</div>

    </Fragment>
  )
}

export default sobremi