import React, { Fragment, useState } from 'react'
import Head from 'next/head'


const [data, setData] = useState<String>();

const sobremi = () => {
  return (
    <Fragment>
      <Head>
        <title>Sobre mi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>sobremi</div>

    </Fragment>
  )
}

export default sobremi